import { Blogpost } from './blog-interface';

export const Blogposts: Blogpost[] = [
  {
    title: 'tjolahopp',
    thumbnailUrl: 'blogPic1',
    body: '11',
    creationDate: new Date('January 3, 2020 02:45:30'),
    likes: 0,
    dislikes: 0,
    comments: [],
    id: 1,
  },
  {
    title: 'chibidibi',
    thumbnailUrl: 'blogPic2',
    body: '22',
    creationDate: new Date('February 4, 2021 03:55:30'),
    likes: 0,
    dislikes: 0,
    comments: [],
    id: 2,
  },
  {
    title: 'tjabatjaba',
    thumbnailUrl: 'blogPic3',
    body: '33',
    creationDate: new Date('March 5, 2022 02:25:30'),
    likes: 0,
    dislikes: 0,
    comments: [],
    id: 3,
  },
  {
    title: 'Helloooo',
    thumbnailUrl: 'blogPic4',
    body: '44',
    creationDate: new Date('April 6, 2022 06:25:30'),
    likes: 0,
    dislikes: 0,
    comments: [],
    id: 4,
  },
  {
    title: 'turboo',
    thumbnailUrl: 'blogPic5',
    body: '55',
    creationDate: new Date('June 7, 2022 08:25:30'),
    likes: 0,
    dislikes: 0,
    comments: [],
    id: 5,
  },
];
