import { Blogpost } from './blog-interface';

export const Blogposts: Blogpost[] = [
  {
    title: 'Velvet Echoes - "Whispers in the Abyss"',
    thumbnailUrl: 'blogPic1',
    body: "`Whispers in the Abyss by Velvet Echoes is a mesmerizing journey into the depths of indie rock, where haunting melodies and introspective lyrics intertwine seamlessly. The album's ethereal soundscapes, coupled with the lead singer's evocative vocals, create an atmosphere that is both melancholic and uplifting. Tracks like 'Lost Horizons' and 'Fading Echoes' showcase the band's ability to craft intricate musical arrangements that linger in the listener's mind. The album's lyrical themes delve into the complexities of human emotions, exploring the subtle nuances of love, loss, and self-discovery. Velvet Echoes succeeds in delivering a debut album that not only captivates with its sonic beauty but also resonates on a profound emotional level.",
    creationDate: new Date('January 3, 2020 02:45:30'),
    likes: 0,
    dislikes: 0,
    comments: ['what a time to be alive'],
    id: 1,
  },
  {
    title: 'Midnight Reverie - "Shadows of the Unseen"',
    thumbnailUrl: 'blogPic2',
    body: '22',
    creationDate: new Date('February 4, 2021 03:55:30'),
    likes: 0,
    dislikes: 0,
    comments: [],
    id: 2,
  },
  {
    title: 'Urban Mirage - "Concrete Dreams"',
    thumbnailUrl: 'blogPic3',
    body: '33',
    creationDate: new Date('March 5, 2022 02:25:30'),
    likes: 0,
    dislikes: 0,
    comments: [],
    id: 3,
  },
  {
    title: 'Nebula Shores - "Astral Echoes"',
    thumbnailUrl: 'blogPic4',
    body: '44',
    creationDate: new Date('April 6, 2022 06:25:30'),
    likes: 0,
    dislikes: 0,
    comments: [],
    id: 4,
  },
  {
    title: 'Sonic Alchemy - "Ephemeral Frequencies"',
    thumbnailUrl: 'blogPic5',
    body: '55',
    creationDate: new Date('June 7, 2022 08:25:30'),
    likes: 0,
    dislikes: 0,
    comments: [],
    id: 5,
  },
];
